config/routes.rb
Teatercamp3::Application.routes.draw do

  get "credit_note/index"

  get "invoices/create"

  resources :products
  resources :users
  resources :sessions
  resources :registrations
  resources :camps
  resources :options
  resources :messages
  resources :categories
  resources :comments
  resources :data_files
  resources :invoices
  resource :session
  resources :posts
  resources :contacts

  resources :pages do
     get :move_higher, :on => :member
     get :move_lower, :on => :member
  end
 root :to => "public#index", :name => "Start"

 get "/logout" => 'sessions#destroy', :as => :logout
 get "login"  => 'sessions#new', :as => :login
 get "/register"  => 'users#create', :as => :register
 get "/signup"  => 'users#new', :as => :signup
 get "/view_emails" => 'registrations#emails', :as => :emails
 get "/set_paid/:id" => 'invoices#set_paid', :as => :set_paid
 # get "/category/:id" => 'public#category', :as => :category
 get "/comments/set_status" => "comments#set_status"
 get "/cms" => 'home#index', :as => :cms
 get "/view_blogg" => 'public#blogg', :as => :view_blogg
 get "/view_camps" => 'public#camps', :as => :view_camps
 get "/view_camp/:id" => 'public#view_camp', :as => :view_camp
 get "/view_page" => 'public#index', :as => :view_page
 get "/add_comment/:id" => "public#add_comment", :as => :add_comment
 get "/view_post" => 'public#view_post', :as => :title
 get 'view/:name' => 'public#view', :as => :view_special
 get 'invoice_send/:id' => 'invoices#invoice_send', :as => :invoice_send
 get 'send_reminder/:id' => 'invoices#reminder_send', :as => :send_reminder
 get 'send_creditnote/:id' => 'invoices#send_creditnote', :as => :send_creditnote
 get 'download_pdf/:id' => 'invoices#download_pdf', :as => :download_pdf
 get 'show_pdf/:id' => 'invoices#show_pdf', :as => :show_pdf
 get 'all_invoices' => 'invoices#all_invoices', :as => :all_invoices
 get 'credit_note/:id' => 'invoices#credit_note', :as => :credit_note
 get 'show_credit_note/:id' => 'invoices#show_credit_note', :as => :show_credit_note
 post '/totals' => 'invoices#totals', :as => :totals
 get '/totals' => 'invoices#totals'







end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  belongs_to :registration
  has_one :credit_note
  has_many :products, through: :registration

  def total_price
    products.sum(:total_price)
  end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  layout :resolve_layout

  def index
    @invoices = Invoice.includes(:registration, :credit_note).where('made_date > ?', Time.now.prev_year(2)).order(made_date:"DESC")
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @invoices }
    end
  end

  def all_invoices
    @invoices = Invoice.includes(:registration, :credit_note)
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @invoices }
    end
  end

  def show
    @invoice = Invoice.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @invoice }
    end
  end

  def show_pdf
    @invoice = Invoice.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @invoice }
    end
  end

  def download_pdf
	  @invoice = Invoice.find(params[:id])
	  html = render_to_string(template: 'invoices/show_pdf/', locals: {invoice: @invoice })
	  pdf = PDFKit.new(html)
	  send_data(pdf.to_pdf, :filename => "faktura_#{@invoice.number}.pdf", :type => 'application/pdf')
	end


  def create
    @invoice = Invoice.new(invoice_params)

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to(@invoice, :notice => 'Invoice was successfully created.') }
        format.xml  { render :xml => @invoice, :status => :created, :location => @invoice }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @invoice.errors, :status => :unprocessable_entity }
      end
    end
  end

  def invoice_send
    @invoice = Invoice.find(params[:id])
    if @invoice.made_date.nil?
      @invoice.made_date = Time.now
      @invoice.pay_by = Time.now + 14.days
    end
    @invoice.sent = true
    @invoice.save
     respond_to do |wants|
       if InvoiceMailer.send_invoice(@invoice).deliver
       wants.js
     end
     end
  end

  def reminder_send
    @invoice = Invoice.find(params[:id])
    @invoice.reminder_date = Time.now
    @invoice.save
    respond_to do |wants|
       if InvoiceMailer.send_reminder(@invoice).deliver
       wants.js
     end
     end
  end
  def set_paid
     @invoice = Invoice.find(params[:id])
    if @invoice.paid == true
      @invoice.paid = false
    else
      @invoice.paid = true
    end
    respond_to do |format|
      if @invoice.save
        format.js

      else
        format.html { render :action => "index" }
        format.xml  { render :xml => @invoice.errors, :status => :unprocessable_entity }
      end
    end
  end
  def credit_note
    @invoice = Invoice.find(params[:id])
    @credit_note = CreditNote.new
    @credit_note.invoice = @invoice
    @credit_note.total = -(@invoice.registration.camp.products.sum(:total_price))
    if @credit_note.save
      respond_to do |wants|
         if InvoiceMailer.send_credit_note(@credit_note).deliver
         wants.js
       end
     end
    end
  end
  def show_credit_note
    @credit_note = CreditNote.find(params[:id])
    @invoice = @credit_note.invoice
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @credit_note }
    end
  end
  def totals
    if !params[:year].nil?
      start_time = (params[:year]).values.join("-").to_time
    else
    start_time = Time.now
    end
    @time = start_time
    @invoices = Invoice.where(:paid => true, :made_date => start_time.beginning_of_year..start_time.end_of_year)
  end

  def resolve_layout
    case action_name
    when "show_pdf"
      "pdf_layout"
    else
      "application"
    end
  end

  private

  def generate_pdf(invoice)
    html = render_to_string(:action => :show_pdf, :layout => false)
    pdf = PDFKit.new(html).to_pdf
    send_data(pdf,
     :filename    => "faktura{@invoice.number }.pdf",
     :disposition => 'attachment')
    Prawn::Document.new do
      text client.name, align: :center
      text "Address: #{client.address}"
      text "Email: #{client.email}"
    end.render
  end
  def invoice_params
    params.require(:invoice).permit(
      :registration_id,
      :number,
      :created_at,
      :updated_at,
      :paid,
      :sent,
      :made_date,
      :pay_by,
      :reminder_date
    )
  end
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/all_invoices.html.erb
<h1>Fakturaer</h1>
<form>
    <input type="text" id="search">
</form>
<table class="tablesorter" cellspacing="0" cellpadding="0">
	<thead>
<tr>
<th class="header">Betalt</th>
<th class="header">Nummer</th>
<th class="header">Navn</th>
<th class="header">Epost</th>
<th class="header">Camp</th>
<th class="header">total</th>
<th class="header"></th>
</tr>
</thead>
<tbody>
<% @invoices.each do |invoice| %>
<tr>
<td>
<% if invoice.sent == true%>
<% if invoice.credit_note.nil? %>
<% if invoice.paid? %>
<a href='#' class='toggle checked' id="paid_<%= invoice.id.to_s %>" data_id='<%= invoice.id.to_s %>'  ref='<%= invoice.id %>'>Ja</a>
<% else %>
<a href='#' class='toggle' id="paid_<%= invoice.id.to_s %>" data_id='<%= invoice.id %>' ref='<%= invoice.id %>'>Nei</a>
<% end %>

<span class="spinning" id="paid_spinning_<%= invoice.id.to_s  %>" style="display:none;"></span>
<% else %>
kreditt
<% end -%>
<% else %>
Ikke sendt
<% end -%>
</td>
<td><%= invoice.number %></td>
<td><%= invoice.registration.name %></td>
<td><%= invoice.registration.billing_email %></td>
<td><%= invoice.registration.camp.name %></td>
<% if invoice.credit_note.nil? %>
<td><%= number_to_currency(invoice.total_price) %></td>
	<% else %>
	<td style="color:red;"><%= number_to_currency(invoice.credit_note.total) %></td>
	<% end -%>
<td>

	<% if invoice.paid == false  %>
	<% if invoice.credit_note.nil? %>
		<% if invoice.sent == true%>
			<% if !invoice.reminder_date.nil? %>
  			Påminnelse sendt <%= invoice.reminder_date.strftime('%d.%m.%Y')%>
  			<span class="send_link_wr"><a class="send_link_reminder" data-object="invoice" data-id="<%= invoice.id.to_s %>">Påminnelse</a></span>
			<% else %>
			   Sendt <%= invoice.made_date.strftime('%d.%m.%Y')%>
			<span class="send_link_wr"><a class="send_link_reminder" data-object="invoice" data-id="<%= invoice.id.to_s %>">Påminnelse</a></span>
			<% end -%>
      <span class="send_link_wr"><a class="send_link_credit" data-object="invoice" data-id="<%= invoice.id.to_s %>">Kreditt</a></span>
    <% else %>
      <span class="send_link_wr"><a class="send_link" id="send_link_<%= invoice.id.to_s  %>"data-object="invoice" data-id="<%= invoice.id.to_s %>">Send</a></span>

    <% end -%>
		<span class="spinning" id="spinning_<%= invoice.id.to_s  %>" style="display:none;"></span>


		<% else %>
	<%= link_to 'Vis_kredit_nota', show_credit_note_path(invoice.credit_note)%>
	<% end -%>

<% end -%>
<%= link_to 'Vis', invoice_path(invoice) %>
  <span class="send_link_wr"><a class="send_link" id="send_link_<%= invoice.id.to_s  %>"data-object="invoice" data-id="<%= invoice.id.to_s %>">Send</a></span>
</td>

</tr>
<% end %>
<tbody>
</table>

app/views/invoices/index.html.erb
<h1>Fakturaer</h1><%= link_to 'Alle Fakturaer', all_invoices_path %>
<form>
    <input type="text" id="search">
</form>
<table class="tablesorter" cellspacing="0" cellpadding="0">
	<thead>
<tr>
<th class="header">Betalt</th>
<th class="header">Nummer</th>
<th class="header">Navn</th>
<th class="header">Epost</th>
<th class="header">Camp</th>
<th class="header">total</th>
<th class="header"></th>
</tr>
</thead>
<tbody>
<% @invoices.each do |invoice| %>
<tr>
<td>
<% if invoice.sent == true%>
<% if invoice.credit_note.nil? %>
<% if invoice.paid? %>
<a href='#' class='toggle checked' id="paid_<%= invoice.id.to_s %>" data_id='<%= invoice.id.to_s %>'  ref='<%= invoice.id %>'>Ja</a>
<% else %>
<a href='#' class='toggle' id="paid_<%= invoice.id.to_s %>" data_id='<%= invoice.id %>' ref='<%= invoice.id %>'>Nei</a>
<% end %>

<span class="spinning" id="paid_spinning_<%= invoice.id.to_s  %>" style="display:none;"></span>
<% else %>
kreditt
<% end -%>
<% else %>
Ikke sendt
<% end -%>
</td>
<td><%= invoice.number %></td>
<td><%= invoice.registration.name %></td>
<td><%= invoice.registration.billing_email %></td>
<td><%= invoice.registration.camp.name %></td>
<% if invoice.credit_note.nil? %>
<td><%= number_to_currency(invoice.total_price) %></td>
	<% else %>
	<td style="color:red;"><%= number_to_currency(invoice.credit_note.total) %></td>
	<% end -%>
<td>

	<% if invoice.paid == false  %>
	<% if invoice.credit_note.nil? %>
		<% if invoice.sent == true%>
			<% if !invoice.reminder_date.nil? %>
  			Påminnelse sendt <%= invoice.reminder_date.strftime('%d.%m.%Y')%>
  			<span class="send_link_wr"><a class="send_link_reminder" data-object="invoice" data-id="<%= invoice.id.to_s %>">Påminnelse</a></span>
			<% else %>
			   Sendt <%= invoice.made_date.strftime('%d.%m.%Y')%>
			<span class="send_link_wr"><a class="send_link_reminder" data-object="invoice" data-id="<%= invoice.id.to_s %>">Påminnelse</a></span>
			<% end -%>
      <span class="send_link_wr"><a class="send_link_credit" data-object="invoice" data-id="<%= invoice.id.to_s %>">Kreditt</a></span>
    <% else %>
      <span class="send_link_wr"><a class="send_link" id="send_link_<%= invoice.id.to_s  %>"data-object="invoice" data-id="<%= invoice.id.to_s %>">Send</a></span>

    <% end -%>
		<span class="spinning" id="spinning_<%= invoice.id.to_s  %>" style="display:none;"></span>


		<% else %>
	<%= link_to 'Vis_kredit_nota', show_credit_note_path(invoice.credit_note)%>
	<% end -%>

<% end -%>
<%= link_to 'Vis', invoice_path(invoice) %>
  <span class="send_link_wr"><a class="send_link" id="send_link_<%= invoice.id.to_s  %>"data-object="invoice" data-id="<%= invoice.id.to_s %>">Send</a></span>
</td>

</tr>
<% end %>
<tbody>
</table>

app/views/invoices/invoice_send.js.erb
$('#spinning_' + <%= escape_javascript( @invoice.id.to_s)  %>).removeClass("spinning").addClass("passed");
$('#send_link_' + <%= escape_javascript( @invoice.id.to_s)  %>).text("Sent nå!")

app/views/invoices/reminder_send.js.erb
$('#spinning_' + <%= escape_javascript( @invoice.id.to_s)  %>).removeClass("spinning").addClass("passed");
$('#send_link_' + <%= escape_javascript( @invoice.id.to_s)  %>).text("Sent nå!")

app/views/invoices/set_paid.js.erb
inv = $('#paid_' + <%= escape_javascript( @invoice.id.to_s)  %>)
if ($(inv).html() == "Nei"){
    	$(inv).html("Ja")
    	}else{
    	$(inv).html("Nei")
   		};
       $(inv).toggleClass("checked");
$("#paid_spinning_" + <%= escape_javascript( @invoice.id.to_s)  %>).hide();

app/views/invoices/show.html.erb
<table class="invoice_show" border="0" cellspacing="5" cellpadding="10">
	<tr><td>Faktura nummer</td>
		<td><%= @invoice.number %></td>
	</tr>
	<tr><td>Deltager</td><td><%= @invoice.registration.name %></td></tr>
	<tr><td>Faktura epost</td><td><%= @invoice.registration.billing_email %></td></tr>
	<tr><td>Kurs</td><td><%= @invoice.registration.camp.name %></td></tr>

	<tr style="font-weight: bold;"><td>Products</td><td>eks mva</td><td>mva</td><td>mva prosent</td><td>total</td></tr>
	<% @invoice.registration.camp.products.each do |product| %>
	<tr><td><%= product.description %></td>
		<td style="text-align: right;"><%= number_to_currency(product.eks_vat) %></td>
		<td style="text-align: right;"><%= number_to_currency(product.vat_in_currency) %></td>
		<td style="text-align: right;"><%=  number_to_percentage(product.vat) %></td>
		<td style="text-align: right;"><%= number_to_currency(product.total_price) %></td>
		</tr>
	
	<% end -%>
	<tr><td style="border-top: 1px solid #000;">Total</td>
	<td style="text-align: right;border-top: 1px solid #000;"><%= number_to_currency(@invoice.registration.camp.total_eks_vat) %></td>
	<td style="text-align: right;border-top: 1px solid #000;"><%= number_to_currency(@invoice.registration.camp.total_vat) %></td>
	<td></td>

	<td style="text-align: right;border-top: 1px solid #000;"><%= number_to_currency(@invoice.registration.camp.products.sum(:total_price)) %></td>
	</tr>
	<% if !@invoice.credit_note.nil? %>
	<tr style="color:red;">
		<td>Kreditnota</td>
		<td> </td>
		<td> </td>
		<td> </td>
		<td><%= @invoice.credit_note.total %></td>
		
	</tr>
	<% end -%>
</table>

app/views/invoices/show_credit_note.html.erb
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<style type="text/css" media="print">
.faktura_wrapper{position: absolute; top: 0; left: 0; }
.faktura_text{position: relative; top: 8cm; left: 0.7cm;max-width: 20cm; display: ;}
.pdf_header{position: absolute; top: 1cm; left:1cm; width: 21cm; font-size: 10px; }
.pdf_info{position: absolute; top: 1cm; left:12cm;  font-size: 10px; }
.invoice_show{max-width: 20cm; font-size: 10px;display: block;}
.invoice_show td {max-width: 4cm;}
.last_lines{position: absolute;top: 18cm; left:1cm;display: block; width: 20cm;font-size: 10px;}
</style>
</head>
<div class="pdf_header">
<h1>Kreditnota for faktura <%= @invoice.number %></h1>


</div>
<div class="pdf_info">
    <p>Andreas Lyngstad</p>
    <p>Org.nr: <%= @vat %></p>
    <p>Åsheimkroken 106</p>
    <p>1820 Spydeberg</p>
    <p>Epost: andreas@lizz.no</p>
    <!-- <p>Kontonr: </p> -->
    <p>Kreditert dato: <%=   @invoice.made_date.strftime('%d.%m.%Y') %></p>
    <p>SKAL IKKE BETALES</p>
    </div>

<div class="faktura_wrapper">

<div class="faktura_text">



<table class="invoice_show" border="0" cellspacing="1" cellpadding="1" >
	<tr><td>Kreditnota nummer</td>
		<td><%= @credit_note.id %></td>

	</tr>
	<tr><td>Deltager</td><td><%= @invoice.registration.name %></td></tr>
	<tr><td>Faktura epost</td><td><%= @invoice.registration.billing_email %></td></tr>
	<tr><td>Kurs</td><td><%= @invoice.registration.camp.name %></td></tr>
	<tr><td>Fra <%= @invoice.registration.camp.begin.strftime('%d.%m.%Y')%></td><td>Til <%= @invoice.registration.camp.end.strftime('%d.%m.%Y') %></td></tr>

	<tr style="font-weight: bold;"><td style=" text-align: left;">Produkter</td>
		<td style=" text-align: right;">Pris</td>
		<td style=" text-align: right;">MVA</td>
		<td style=" text-align: right;">Pris ink MVA</td>
		<td style=" text-align: right;">MVA %</td>
		</tr>
	<% @invoice.registration.camp.products.each do |product| %>
	<tr><td><%= product.description %></td>
		<td style="text-align: right;">- <%= number_to_currency(product.eks_vat) %></td>
		<td style="text-align: right;">- <%= number_to_currency(product.vat_in_currency) %></td>

		<td style="text-align: right;">- <%= number_to_currency(product.total_price) %></td>
		<td style="text-align: right;">- <%=  number_to_percentage(product.vat) %></td>
		</tr>

	<% end -%>
	<tr><td style="border-top: 1px solid #000;">Total</td>
	<td style="text-align: right;border-top: 1px solid #000;">- <%= number_to_currency(@invoice.registration.camp.total_eks_vat) %></td>
	<td style="text-align: right;border-top: 1px solid #000;">- <%= number_to_currency(@invoice.registration.camp.total_vat) %></td>


	<td style="text-align: right;border-top: 1px solid #000;">- <%= number_to_currency(@invoice.registration.camp.products.sum(:total_price)) %></td>
	<td></td>
	</tr>


</table>
</div>
<div class='last_lines'>
<p>Beløp - <%= number_to_currency(@invoice.registration.camp.products.sum(:total_price)) %> </p>
 </div>
  </div>

app/views/invoices/show_pdf.html.erb
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<style type="text/css" media="print">
.faktura_wrapper{position: absolute; top: 0; left: 0; }
.faktura_text{position: relative; top: 8cm; left: 0.7cm;max-width: 20cm; display: ;}
.pdf_header{position: absolute; top: 1cm; left:1cm; width: 21cm; font-size: 10px; }
.pdf_info{position: absolute; top: 1cm; left:12cm;  font-size: 10px; }
.invoice_show{max-width: 20cm; font-size: 10px;display: block;}
.invoice_show td {max-width: 4cm;}
.last_lines{position: absolute;top: 18cm; left:1cm;display: block; width: 20cm;font-size: 10px;}
</style>
</head>
<div class="pdf_header">
<h1>Faktura for <%= @invoice.registration.camp.name %></h1>


</div>
<div class="pdf_info">
    <p>Andreas Lyngstad</p>
    <p>Org.nr: <%= @vat %></p>
    <p>Åsheimkroken 106</p>
    <p>1820 Spydeberg</p>
    <p>Epost: andreas@lizz.no</p>
    <p>Kontonr: <%= @account %></p>
    <p>Faktura dato: <%=   @invoice.made_date.strftime('%d.%m.%Y') %></p>
    <p>Faktura forfall: <%=   @invoice.pay_by.strftime('%d.%m.%Y') %></p>
    </div>

<div class="faktura_wrapper">

<div class="faktura_text">



<table class="invoice_show" border="0" cellspacing="1" cellpadding="1" >
	<tr><td>Faktura nummer</td>
		<td><%= @invoice.number %></td>

	</tr>
	<tr><td>Deltager</td><td><%= @invoice.registration.name %></td></tr>
	<tr><td>Faktura epost</td><td><%= @invoice.registration.billing_email %></td></tr>
	<tr><td>Kurs</td><td><%= @invoice.registration.camp.name %></td></tr>
	<tr><td>Fra <%= @invoice.registration.camp.begin.strftime('%d.%m.%Y')%></td><td>Til <%= @invoice.registration.camp.end.strftime('%d.%m.%Y') %></td></tr>

	<tr style="font-weight: bold;"><td style=" text-align: left;">Produkter</td>
		<td style=" text-align: right;">Pris</td>
		<td style=" text-align: right;">MVA</td>
		<td style=" text-align: right;">Pris ink MVA</td>
		<td style=" text-align: right;">MVA %</td>
		</tr>
	<% @invoice.registration.camp.products.each do |product| %>
	<tr><td><%= product.description %></td>
		<td style="text-align: right;"><%= number_to_currency(product.eks_vat) %></td>
		<td style="text-align: right;"><%= number_to_currency(product.vat_in_currency) %></td>

		<td style="text-align: right;"><%= number_to_currency(product.total_price) %></td>
		<td style="text-align: right;"><%=  number_to_percentage(product.vat) %></td>
		</tr>

	<% end -%>
	<tr><td style="border-top: 1px solid #000;">Total</td>
	<td style="text-align: right;border-top: 1px solid #000;"><%= number_to_currency(@invoice.registration.camp.total_eks_vat) %></td>
	<td style="text-align: right;border-top: 1px solid #000;"><%= number_to_currency(@invoice.registration.camp.total_vat) %></td>


	<td style="text-align: right;border-top: 1px solid #000;"><%= number_to_currency(@invoice.registration.camp.products.sum(:total_price)) %></td>
	<td></td>
	</tr>


</table>
</div>
<div class='last_lines'>
<p>Beløp <%= number_to_currency(@invoice.registration.camp.products.sum(:total_price)) %> til konto <%= @account %></p>
 </div>
  </div>

app/views/invoices/totals.html.erb
<%= form_tag totals_path %>
<%= datetime_select "year", :start_time, {:discard_hour => true,:discard_m => true,:discard_day => true, :discard_month => true, :start_year => 2011}%>
<%= submit_tag "finn" %>

<p><b><%= @time.strftime("%Y") %></b></p>
<table border="0" cellspacing="10" cellpadding="10">

	<tr>
		<th>Total</th>
		<th>Vat</th>
		<th>Eks_vat</th>
	</tr>

	<tr>

		<td style="text-align: right;"><%= number_to_currency(total(@invoices)[0]) %></td>



		<td style="text-align: right;"><%= number_to_currency(total(@invoices)[1]) %></td>


		<td style="text-align: right;"><%= number_to_currency(total(@invoices)[2]) %></td>
	</tr>

</table>

<%=@invoices.count%>