config/routes.rb
Teatercamp3::Application.routes.draw do

  get "credit_note/index"

  get "invoices/create"

  resources :products
  resources :users
  resources :sessions
  resources :registrations
  resources :camps
  resources :options
  resources :messages
  resources :categories
  resources :comments
  resources :data_files
  resources :invoices
  resource :session
  resources :posts
  resources :contacts

  resources :pages do
     get :move_higher, :on => :member
     get :move_lower, :on => :member
  end
 root :to => "public#index", :name => "Start"

 get "/logout" => 'sessions#destroy', :as => :logout
 get "login"  => 'sessions#new', :as => :login
 get "/register"  => 'users#create', :as => :register
 get "/signup"  => 'users#new', :as => :signup
 get "/view_emails" => 'registrations#emails', :as => :emails
 get "/set_paid/:id" => 'invoices#set_paid', :as => :set_paid
 # get "/category/:id" => 'public#category', :as => :category
 get "/comments/set_status" => "comments#set_status"
 get "/cms" => 'home#index', :as => :cms
 get "/view_blogg" => 'public#blogg', :as => :view_blogg
 get "/view_camps" => 'public#camps', :as => :view_camps
 get "/view_camp/:id" => 'public#view_camp', :as => :view_camp
 get "/view_page" => 'public#index', :as => :view_page
 get "/add_comment/:id" => "public#add_comment", :as => :add_comment
 get "/view_post" => 'public#view_post', :as => :title
 get 'view/:name' => 'public#view', :as => :view_special
 get 'invoice_send/:id' => 'invoices#invoice_send', :as => :invoice_send
 get 'send_reminder/:id' => 'invoices#reminder_send', :as => :send_reminder
 get 'send_creditnote/:id' => 'invoices#send_creditnote', :as => :send_creditnote
 get 'download_pdf/:id' => 'invoices#download_pdf', :as => :download_pdf
 get 'show_pdf/:id' => 'invoices#show_pdf', :as => :show_pdf
 get 'all_invoices' => 'invoices#all_invoices', :as => :all_invoices
 get 'credit_note/:id' => 'invoices#credit_note', :as => :credit_note
 get 'show_credit_note/:id' => 'invoices#show_credit_note', :as => :show_credit_note
 post '/totals' => 'invoices#totals', :as => :totals
 get '/totals' => 'invoices#totals'







end

app/models/camp.rb
class Camp < ActiveRecord::Base
  has_many :registrations
  # validates :name, :description, :age1, :age2, :begin, :end, presence: true
  validates_presence_of :name, :description, :age1, :age2, :begin, :end


  # validates_length_of :ingress, :maximum => 440, :allow_blank => true
  has_many :pricings, inverse_of: :camp
  has_many :products, :through => :pricings
  accepts_nested_attributes_for :pricings
   def total_eks_vat
     a = 0
     products.each do |p|
       a += p.eks_vat
     end
     a
   end
   def total_vat
     products.sum(:total_price) - total_eks_vat
   end
end

app/controllers/camps_controller.rb
class CampsController < ApplicationController
  # GET /camps
  # GET /camps.xml
  layout "application"
    def index
    @camps = Camp.order("public DESC").includes(:registrations)
    if request.get? && !params[:id].blank?
      @camp = Camp.find(params[:id])
      elsif request.get? && params[:id].blank?
      @camp = Camp.new
      elsif request.post? && !params[:id].blank?
      @camp = Camp.find(params[:id])
      if params[:commit] == "oppdater"
        respond_to do |format|
          if @camp.update_attributes(params[:camp])
            flash[:notice] = 'Kurset ble oppdatert'
            format.html { redirect_to(:action => "index") }
            format.xml  { head :ok }
          else
            format.html { render :action => "index" }
            format.xml  { render :xml => @camp.errors }
          end
      end
      end
    end
  end

 def new
   @camp = Camp.new
   @products = Product.all
 end
 def edit
   @camp = Camp.find(params[:id])
   @products = Product.all
 end
  # GET /camps/1
  # GET /camps/1.xml
  def show
    @camp = Camp.find(params[:id])
    @camps = Camp.all

    respond_to do |format|
      format.html { render :action => "show" }
      format.xml  { render :xml => @camp }
    end
  end


  def create
    @camp = Camp.new(camp_params)
    @camps = Camp.all
    @products = Product.all
    respond_to do |format|
      if @camp.save
        flash[:notice] = 'Kurset ble laget.'
        format.html { redirect_to(camps_path) }
        format.xml  { render :xml => @camp, :status => :created, :location => @camp }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @camp.errors, :status => :unprocessable_entity }
      end
    end
  end
 def update
   @camp = Camp.find(params[:id])
   @products = Product.all
    params[:camp][:product_ids] ||= []

    respond_to do |format|
      if @camp.update(camp_params)

        flash[:notice] = 'Campen ble oppdatert.'
        format.html { redirect_to(camps_path) }
        format.xml  { head :ok }
      else
        flash[:notice] = 'Feil'
        format.html { render :action => "edit" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
 end

  # DELETE /camps/1
  # DELETE /camps/1.xml
  def destroy
    @camp = Camp.find(params[:id])
    @camp.destroy

    respond_to do |format|
        flash[:notice] = 'Kurset er slettet'
      format.html { redirect_to(camps_url) }
      format.xml  { head :ok }
    end
  end
  private
  def camp_params
    params.require(:camp).permit(:name,:description,
      :age1,:age2,:begin,:end,:participants,:public,:ingress, :product_ids =>[] )
  end
end

app/helpers/camps_helper.rb
module CampsHelper
  
 
end

app/views/camps/_form.html.erb
<li>
<%= label_tag 'Navn' %>
<%= f.text_field :name %>
</li>

<li>
<%= label_tag 'Ingress' %>
<%= f.text_area :ingress %>
</li>

<li>
<%= label_tag 'Beskrivelse' %>
<%= f.text_area :description %>
</li>


<li>
<%= label_tag 'Alder fra - til' %>
<%= f.select :age1, 1..99 %>
<%= f.select :age2, 1..99 %>
</li>

<li>
<%= label_tag 'Begynner' %>
<%= f.date_select :begin, :start_year => Time.now.year, :order => [:day,:month,:year]  %>
</li>

<li>
<%= label_tag 'Slutter' %>
<%= f.date_select :end, :start_year => Time.now.year, :order => [:day,:month,:year] %>
</li>

<li>
<%= label_tag 'Antall deltagere' %>
<%= f.select :participants, 1..40 %>

</li>
<li>
<%= label_tag 'Produkter' %><li>
	<% @products.each do |product| -%>
	<li><%= check_box_tag('camp[product_ids][]', product.id, @camp.products.map {|c| c.id }.include?(product.id), :class => "pro_check") %>
	<%= product.description %></li>
	<% end %>


<li>
<%= label_tag 'Offentlig' %>
<%= f.select :public,  [['Ja', true], ['Nei', false], ] %>
</li>

app/views/camps/_list.html.erb
<h1>Alle kurs</h1>
<p><%= link_to "Nytt kurs", new_camp_path%></p>

<table class="tablesorter" cellspacing="0" cellpadding="0">
	<thead>
	<tr>
		<th class="header">Navn</th>
		<th class="header">Offentlig</th>
		<th class="header">Påmeldinger</th>
		<th class="header">Antall deltagere</th>
	    <th class="header">Beskrivelse</th>
	    <th class="header">Alder</th>
	    <th class="header">Begynner</th>
	    <th class="header">Slutter</th>
		<th></th>
	</tr>
	</thead>
<tbody>
	<% @camps.each do |camp| %>
	<tr id="<%=camp.id %>">
	<% if params[:id] == camp.id.to_s%>
	<tr id="<%= params[:id] %>" style="background:#999999">
  		<% end %>

	    <td><%=h camp.name %></td>
	    <% if camp.public == false %>
	    	    <td>nei</td>
	    	 <% else %>
	    	   <td>ja</td>
	    	   <% end %>
		<td><%=h camp.registrations.count %></td>
		<td><%=h camp.participants %></td>
	    <td><%=h truncate(h(camp.description), :length => 35)%></td>
	    <td><%=h camp.age1 %> - <%=h camp.age2 %> år</td>
	    <td><%=h camp.begin.strftime('%d.%m.%Y')%></td>
	    <td><%=h camp.end.strftime('%d.%m.%Y') %></td>
	    <td>
	    	<%= link_to 'Vis', camp_path(camp) %>
	    	<%= link_to 'Oppdater', edit_camp_path(camp) %>
	   	</td>
  	</tr>

<% end %>
	<tbody>
</table>

app/views/camps/_list_form.html.erb
<%= render :partial => "list" %>

app/views/camps/_single.html.erb
<h1><%= @camp.name %>|<%= link_to "Vis alle", camps_path %>|<%= link_to 'Oppdater', edit_camp_path(@camp) %></h1>

<p><%= @camp.description %></p>
<p>Fra <%= @camp.age1 %>år til<%= @camp.age2%>år</p>
<p><%= @camp.begin.strftime('%d.%m.%Y') %> - <%= @camp.end.strftime('%d.%m.%Y') %></p>
<p>Offentlig: 
	<% if @camp.public == true %>
	Ja
	<% else %>
	Nei
	<% end -%>
</p>

<p></p>
<h3>Produkter</h3>
<table class="tablesorter" cellspacing="0" cellpadding="0">
	<thead>
	<tr>
		<th>Produkt</th>
		<th>Pris</th>
	</tr>
	</thead>
	<tbody> 
	<% @camp.products.each do |product| %>
	<tr>
		<td><%= product.description %></td>
		<td><%= number_to_currency(product.total_price )%></td>	
	</tr>
	<% end %>
	<tr bordercolor="#000">
		<td>Total</td>
		<td><%= number_to_currency(@camp.products.sum(:total_price)) %></td>	
	</tr>
	<tbody>
</table>


<h3>Påmeldte: <%= @camp.registrations.count%> </h3>
<table class="tablesorter" cellspacing="0" cellpadding="0">
	<thead>
	<tr>
		<th>Navn</th>
		<th>Alder</th>
		
	</tr>
	</thead>
	<tbody>
<%@camp.registrations.each do |reg|%>
<tr>
		<td><%= reg.name %></td>
		<td><%= reg.age %></td>
		<td><%= link_to("Vis", registration_path(reg))%>
			<%= link_to 'slett', reg, :confirm => 'Er du sikker?', :method => :delete %>
		</td>
			
	</tr>
<% end %>

<tbody>
</table>

app/views/camps/edit.html.erb
<h2>Oppdater kurs</h2>
	<%= form_for @camp do |f| -%>
	<%=  render "shared/error_message", :target => @camp %>
	<ul class="form_layout">	
		<%= render( :partial => "form", :locals => {:f => f})%>
		<li><label>&nbsp;</label><%= f.submit('Lagre',:class => 'submit') %></li>
	</ul>	
	<% end -%>

app/views/camps/index.html.erb
<% @page_title = "kurs" -%>

<%= render :partial => "list_form" %>

app/views/camps/new.html.erb
<h2>Nytt kurs</h2>
	<%= form_for @camp do |f| -%>
	 <%=  render "shared/error_message", :target => @camp %>
	<ul class="form_layout">	
		<%= render( :partial => "form", :locals => {:f => f})%>
		<li><label>&nbsp;</label><%= f.submit('Lagre',:class => 'submit') %></li>
	</ul>	
	<% end %>
	

app/views/camps/show.html.erb
<% @page_title = "kurs" -%>

<%= render :partial => "single" %>