config/routes.rb
Teatercamp3::Application.routes.draw do

  get "credit_note/index"

  get "invoices/create"

  resources :products
  resources :users
  resources :sessions
  resources :registrations
  resources :camps
  resources :options
  resources :messages
  resources :categories
  resources :comments
  resources :data_files
  resources :invoices
  resource :session
  resources :posts
  resources :contacts

  resources :pages do
     get :move_higher, :on => :member
     get :move_lower, :on => :member
  end
 root :to => "public#index", :name => "Start"

 get "/logout" => 'sessions#destroy', :as => :logout
 get "login"  => 'sessions#new', :as => :login
 get "/register"  => 'users#create', :as => :register
 get "/signup"  => 'users#new', :as => :signup
 get "/view_emails" => 'registrations#emails', :as => :emails
 get "/set_paid/:id" => 'invoices#set_paid', :as => :set_paid
 # get "/category/:id" => 'public#category', :as => :category
 get "/comments/set_status" => "comments#set_status"
 get "/cms" => 'home#index', :as => :cms
 get "/view_blogg" => 'public#blogg', :as => :view_blogg
 get "/view_camps" => 'public#camps', :as => :view_camps
 get "/view_camp/:id" => 'public#view_camp', :as => :view_camp
 get "/view_page" => 'public#index', :as => :view_page
 get "/add_comment/:id" => "public#add_comment", :as => :add_comment
 get "/view_post" => 'public#view_post', :as => :title
 get 'view/:name' => 'public#view', :as => :view_special
 get 'invoice_send/:id' => 'invoices#invoice_send', :as => :invoice_send
 get 'send_reminder/:id' => 'invoices#reminder_send', :as => :send_reminder
 get 'send_creditnote/:id' => 'invoices#send_creditnote', :as => :send_creditnote
 get 'download_pdf/:id' => 'invoices#download_pdf', :as => :download_pdf
 get 'show_pdf/:id' => 'invoices#show_pdf', :as => :show_pdf
 get 'all_invoices' => 'invoices#all_invoices', :as => :all_invoices
 get 'credit_note/:id' => 'invoices#credit_note', :as => :credit_note
 get 'show_credit_note/:id' => 'invoices#show_credit_note', :as => :show_credit_note
 post '/totals' => 'invoices#totals', :as => :totals
 get '/totals' => 'invoices#totals'







end

app/views/shared/_comment.html.erb
<p>
<p style="text-decoration: underline;">	
Skrevet av: <%= h(comment.author)%>,<em><%=h(comment.created_at.strftime("%d. %B %Y"))%></em></p>
<%= h(comment.content) %>

</p>

app/views/shared/_error_message.html.erb
<% if target.errors.any? %>
<div id="errorExplanation">
  <h2>Kunne ikke lagre pågrunn av <%= target.errors.count %> feil</h2>
  <ul>
  <% target.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    
  <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_error_messages.html.erb
<div class="errorExplanation" id="errorExplanation">
  <h2>Kunne ikke sende påmeldingen på grunn av følgende feil.</h2>
  
</div>

app/views/shared/_links.html.erb
<div id="sub_nav">
	<ul>
		<li><h3>Kategorier</h3></li>
		<% @all_categories.each do |cat| -%>
		<li><b><%= link_to_unless_current(cat.name, category_path(cat)) %></b></li>
		<% end %>
	</ul>
	<ul>
		<li><h3>Alle innlegg</h3></li>
		<% for post in @posts_til_liste -%>
		
		<li><b><%= link_to_unless_current(h(post.title), :controller => "public", :action => "view_post", :id => post.id) %></b></li>
		<%end -%>
		</ul>
	
</div>

<div id="search_form">
	Søk i bloggen
	<%= form_tag posts_path, :method => 'get' do %>
	 	<%= text_field_tag :search, params[:search] %>
	    <%= submit_tag "Søk", :name => nil, :class => 'submit' %>
	<% end %>			
</div>

app/views/shared/_newcomment.html.erb
	
<h3>Skriv kommentar</h3>

<p style="color: red"><%= flash[:error] %></p>
<p style="color: green"><%= flash[:notice] %></p>
<%= form_for(Comment.new, :url => add_comment_path(@post.id)) do |f|%>
	<ul class="form_layout">
		<li><label>Ditt navn:</label><%= f.text_field(:author)%></li>
		<li><label>Din e-post:</label><%= f.text_field(:author_email) %></li>
		<li><label>Kommentar:</label><%= f.text_area(:content, :cols => 60, :rows => 5 )%></li>
		<li><label>&nbsp;</label><%= f.submit("Lagre", :class => 'submit') %></li>
	</ul>	
<% end -%>

app/views/shared/_post.html.erb
<% for post in @posts %>
	<div class="post">
		<h2><%= link_to(h(post.title), :controller => "public", :action => "view_post", :id => post.id) %></h2>
		<div>
			<strong>Av: <%= h(post.author.full_name) %></strong>  <em><%= h(post.created_at.strftime("%d. %m. %Y")) %></em>
			<em><%= post.categories.collect {|cat| cat.name if !cat.nil?}.to_sentence%></em>

		</div>
		<p><%= raw(post.lead) %></p>
		<% if post.approved_comments.size != 0 -%>
		<p>
		<strong><%= link_to(('Antall kommentarer:' + " " + (post.approved_comments.size.to_s) ), :action => 'view_post', :id => post.id, :anchor => 'comments')%></strong>
				</p>
			<% end%>
	
		
	</div>
<% end %>

app/views/shared/_recent_posts.html.erb
<h3>Siste innlegg i bloggen</h3>

app/views/shared/view_post.html.erb
<% @page_title = "Nyheter"%>
<%= render "nav" %>
<div id="blogg_l">
	<%= link_to "Vis alle", view_blogg_path, :style => "float:right;"%>
	<h1><%= @post.title %></h1>
		Av: <%= @post.author.full_name %>, <em><%= @post.created_at.strftime("%d. %B %Y") %>.</em>
	<p><b><%= raw(@post.lead) %></b></p>
	<p><%= raw(@post.content) %></p>
</div>
<div id="content_r">
	<%= render :partial => "shared/links" %>
</div>